[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14
normal = { style = "Regular", family = "JetBrainsMono Nerd Font" }

[window]

dynamic_padding = false

startup_mode = "Maximized"

dynamic_title = true
opacity = 0.8

[terminal.shell]
program = "zellij"
