[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14
normal = { style = "Regular", family = "Iosevka Nerd Font Mono" }

[window]
dynamic_padding = false
decorations = "none"
startup_mode = "Maximized"
opacity = 0.9

[terminal.shell]
program = "zellij"
