[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14
normal = { style = "Regular", family = "RecMonoCasual Nerd Font Propo" }

[window]

dynamic_padding = false
startup_mode = "Fullscreen"
decorations = "none"

dynamic_title = true
opacity = 0.9
